language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
- iojs
script:
- npm test
after_script:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- cat ./coverage/lcov.info | ./node_modules/.bin/codecov
deploy:
  provider: npm
  email: dev@adrianhaasler.com
  api_key:
    secure: FQcDHSb5ZZSsoebz76fGIUeTPP9MIjmIH0Az6oqpCmoUULYzmDddjFmjeUsNVPNPwbBEDOhrpVrhIPJeO1hHvAs2kH5uIIbR5FOeSsmH3r515vfLf8DGp1RsTX9xyYlSQ7OQS0sfLFQhc3zYZiJP03w0Z3qqL7RYI6KKnyyLSWvgNJw5uikfJmKGO+hpFkQep4LgbFDxjg2RQ8eg2+3BhmrwRax/+F2z8IhuqMComdjouxsyTAKDyEsagV6YO1pa+YR1t4b7eNvpzBE9PCzy+XYGUGubc5kAcwqKclGmhhUbxzOivGJa9u5hlGWMbYUnw3HG58VvGxh9scOw4pesebN/o1G37ZwKGxmi1Rj2TBqquieLGMhLVYEUQ5HNaO+lgStCxozsz/fBY6OiipXcTZdVCTBgkuxzS0/7yWZgtDSqs1pUuZviCFsJ7bAwo1+lunrsoVrppT3m9R+gBwDSg9fPvbqkLcRpUCb/fWVou1b+JgneKuA8yzXabnd8I0CvolASyblMFgLScaFUGsz4FvKTBOjM79hMWPkiKevBkWUvQhrKZ+pr31KsgMA8GF/DS4yEq/n5nwBCIkz6oykuUC8qjp2DBEuSnw5U/j5xoINCAfB7z/a3m23gzyD8zy/vAql7tIvhllZZzmKSXUrCZwRjXSa6i5Kbf2e8QMrOJ2Q=
  on:
    tags: true
    repo: ahaasler/hexo-multilingual
    node: '0.12'
addons:
  code_climate:
    repo_token:
      secure: WR1A/yLHm5NQb76vbGO14ZHAeUkF+/N1LhbyDGYo7WCtg5yfiIapp4B0hWpmPovTIjwENtpDPq6SPadXwUC632UeQa5MqdfbEP/Ss/oVL8jydXolsju4Z8ICgWsNWPXMPMfXYxqo90vsOZBx3biD/3tLdWfH1YwsbS+VQYKYsYvGvAAT3OjbRN74wlhk6MwqBbeqovbLcNVXwmLZNypd4rWP+HDEGpqk2gPYlaCQTy4ZvWXRTWoF/wMFQ4X32wR2fHvs4A+LQyGxzaDZ3zAFMO1TfbSoDjlKaNHqe1Hs/7dl+ehwygI46Wc0X0Fakg3wGTRChio9UAUyRInj+FLScuihQ++zgAOzt5Yp5ZOKKRQltENHrqcd/504QllywgenVGX4h/gXjHj736+AHPVoEhaLfw4jhmmcLr1bu9ghVo6RP9bfs/Mz3jodH9V0dIVy8OdLNFVgj2eDBvGEiafaYyKy4xN8pe8BmTfD4ab1LW9HKOM4R7YOwfM6ecTGNSKhZCOp46awIBb41VOAAZwOZ8ckaWXW45CfPTq+WUqop9glYPBcPwusqHb8pWUcm5s891AE7tFcfBt58bYJz8qFylH+VFeUD8ua33Pzagevu87r2ETN1X+sgvwthMCEb3tL/v9kXxDV1jepjC5Gj4vFjSXzmTuk5VXAP1FM/A2IRWQ=
